SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[newTest] (
		[Column_2]     [int] NULL
)
GO
ALTER TABLE [dbo].[newTest] SET (LOCK_ESCALATION = TABLE)
GO
