SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Customer] (
,
		CONSTRAINT [Customer_PK]
		PRIMARY KEY
		CLUSTERED
		([CustomerId])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[Customer] SET (LOCK_ESCALATION = TABLE)
GO
